# @package _group_
env: "Hopper-v3"
wandb_project: "garage-hopper"

p_tremble: 0.0
reset_prob: 0.5
reset_type: "bc_rollin" # options: "expert_reset", "subopt_reset", "bc_rollin"
total_env_steps: 500_000
eval_frequency: 50_000
expert_dataset_size: 600
subopt_dataset_size: 25_000
subopt_tremble: 0.05
bc_init_steps: 0
sampling_schedule: [[0.2, 0.1, 200000], [0.1, 0.01, 1000000]]

train_discriminator: true
discriminator:
  lr: 8e-4
  train_every: 5000
  num_sample_trajectories: 4
  num_update_steps: 1
  batch_size: 4096
  clip_output: false
  ensemble_size: 1  # 1 is equivalent to no ensemble

actor:
  bc_reg: False
  bc_weight: 1.0
  policy: "MlpPolicy"
  policy_kwargs:
    net_arch: [256, 256]
  train_freq: 64
  gradient_steps: 64
  gamma: 0.98
  tau: 0.02
